language: java
jdk: oraclejdk11

script: mvn -e verify

before_install:
  - chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - musin.idris@gmail.com
    on_failure: always
    on_success: change